export default interface Discovery {
    register_prospect_savings_web: string,
    register_prospect_savings_mgm: string,
    pusher_auth_channel: string,
    register_prospect_debit: string,
    reset_password: string,
    register_prospect_ultraviolet_web: string,
    business_card_waitlist: string,
    register_prospect: string,
    register_prospect_savings_request_money: string,
    register_prospect_global_web: string,
    register_prospect_c: string,
    request_password_reset: string,
    auth_gen_certificates: string,
    login: string,
    email_verify: string,
    ultraviolet_waitlist: string,
    auth_device_resend_code: string,
    msat: string,
}